### ISSUE TITLE
Not working on ASUS Chromebook flip c100p with lid closed

### ISSUE THREAD

**Issue by GeitHub** [StrawnPoint04/WakeUp#2]
using the terminal, though this works (it'd just be easier to have an app interface do it for me)

> open terminal
> shell
> sudo stop powerd
> (when finished)
> sudo start powerd
> returns everything to normal

**Comment by kennystrawnmusic** [comment]
That's an API limitation, not an app limitation. See https://bugs.chromium.org/p/chromium/issues/detail?id=287071
